// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ess
arma::mat ess(int n_iterations, arma::mat A, arma::vec b, arma::vec x_init, bool mode, bool verbose);
RcppExport SEXP _lincongauss_ess(SEXP n_iterationsSEXP, SEXP ASEXP, SEXP bSEXP, SEXP x_initSEXP, SEXP modeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_init(x_initSEXP);
    Rcpp::traits::input_parameter< bool >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(ess(n_iterations, A, b, x_init, mode, verbose));
    return rcpp_result_gen;
END_RCPP
}
// test_update_fix_shift
arma::uvec test_update_fix_shift(arma::mat A, arma::vec b, double fraction, double shift, arma::vec shiftvals);
RcppExport SEXP _lincongauss_test_update_fix_shift(SEXP ASEXP, SEXP bSEXP, SEXP fractionSEXP, SEXP shiftSEXP, SEXP shiftvalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type fraction(fractionSEXP);
    Rcpp::traits::input_parameter< double >::type shift(shiftSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type shiftvals(shiftvalsSEXP);
    rcpp_result_gen = Rcpp::wrap(test_update_fix_shift(A, b, fraction, shift, shiftvals));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lincongauss_ess", (DL_FUNC) &_lincongauss_ess, 6},
    {"_lincongauss_test_update_fix_shift", (DL_FUNC) &_lincongauss_test_update_fix_shift, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_lincongauss(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
