---
title: "Implementation Comparison"
author: "Patrick Ding"
date: "8/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Unit Gaussian

### Rcpp implementation

```{r params}
n_rep <- 30

d <- 4
mu <- rep(0, d)
Sigma <- diag(d)
lb <- rep(0, d)
ub <- rep(Inf, d)

set.seed(0)
rcpp_ests <- rep(NA, n_rep)
times <- rep(NA, n_rep)

for (i in 1:n_rep) {
  t_start <- tictoc::tic()
  rcpp_ests[i] <- lincongauss::ptmvn(mu, Sigma, lb, ub, 
                               n_sub_samples = 512, n_sub_skip = 1,
                               n_hdr_samples = 512, n_hdr_skip = 1)
  t_stop <- tictoc::toc()
  times[i] <- t_stop$toc - t_stop$tic
}
```

```{r}
boxplot(rcpp_ests, main = "Rcpp estimates vs true value")
abline(h = 1 / 2^d)
# boxplot(py$py_ests)
# abline(h = 1 / 2^d)
```

```{r}
boxplot(times, main = "Rcpp times")
```
## Dense covariance

```{r}
n_rep <- 40

d <- 10
mu <- rep(0, d)
Sigma <- .5 * diag(d) + .5 * rep(1, d) %*% t(rep(1, d))
lb <- rep(0, d)
ub <- rep(Inf, d)

set.seed(0)
rcpp_ests <- rep(NA, n_rep)
times <- rep(NA, n_rep)

for (i in 1:n_rep) {
  t_start <- tictoc::tic()
  rcpp_ests[i] <- lincongauss::ptmvn(mu, Sigma, lb, ub, 
                               n_sub_samples = 9, n_sub_skip = 1,
                               n_hdr_samples = 256, n_hdr_skip = 1)
  t_stop <- tictoc::toc()
  times[i] <- t_stop$toc - t_stop$tic
}
```

```{r}
boxplot(rcpp_ests, main = "Rcpp estimates vs true value")
abline(h = 1 / (d+1))

boxplot(times, main = "Rcpp times")
```


```{r}
d <- 2
mu <- rep(0, d)
Sigma <- .5 * diag(d) + .5 * rep(1, d) %*% t(rep(1, d))
lb <- rep(0, d)
ub <- rep(Inf, d)

samples <- lincongauss::rtmvn(1000, mu, Sigma, lb, ub)

botev_samples <- TruncatedNormal::rtmvnorm(1000, mu, Sigma, lb, ub)

plot(samples)
points(botev_samples, col = "red")


cor(samples[, c(1, 2)])
cor(botev_samples[, 1:2])
```
