# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ess <- function(n_iterations, A, b, x_init, mode, verbose) {
    .Call(`_lincongauss_ess`, n_iterations, A, b, x_init, mode, verbose)
}

test_update_fix_shift <- function(A, b, fraction, shift, shiftvals) {
    .Call(`_lincongauss_test_update_fix_shift`, A, b, fraction, shift, shiftvals)
}

